{"spans": [{"trace_id": "fTOOFTiGu0lcnbIVSkewMQ==", "span_id": "rNhyTzfLpZM=", "trace_state": "", "parent_span_id": "", "name": "LangGraph", "start_time_unix_nano": 1759697139453066000, "end_time_unix_nano": 1759697139462706800, "attributes": {"metadata": "{\"thread_id\": \"1\"}", "mlflow.spanType": "\"CHAIN\"", "mlflow.spanInputs": "{\"details\": \"Search for an entity named Axact\", \"transaction_file\": null}", "mlflow.traceRequestId": "\"tr-7d338e153886bb495c9db2154a47b031\""}, "events": [{"time_unix_nano": 1759697139462706, "name": "exception", "attributes": {"exception.message": "'input_str'", "exception.type": "KeyError", "exception.stacktrace": "Traceback (most recent call last):\n  File \"C:\\Users\\tejsh\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\langgraph\\pregel\\main.py\", line 2657, in stream\n    for _ in runner.tick(\n  File \"C:\\Users\\tejsh\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\langgraph\\pregel\\_runner.py\", line 162, in tick\n    run_with_retry(\n  File \"C:\\Users\\tejsh\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\langgraph\\pregel\\_retry.py\", line 42, in run_with_retry\n    return task.proc.invoke(task.input, config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\tejsh\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\langgraph\\_internal\\_runnable.py\", line 657, in invoke\n    input = context.run(step.invoke, input, config, **kwargs)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\tejsh\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\langgraph\\_internal\\_runnable.py\", line 401, in invoke\n    ret = self.func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\tejsh\\AppData\\Local\\Temp\\ipykernel_14544\\4021691321.py\", line 31, in start_node\n    HumanMessage(content=state['input_str'])\n                         ~~~~~^^^^^^^^^^^^^\nKeyError: 'input_str'\nDuring task with name 'start_node' and id '84813bed-3166-803f-e4a5-fa4d5a5a8a9e'"}}], "status": {"message": "'input_str'", "code": "STATUS_CODE_ERROR"}}, {"trace_id": "fTOOFTiGu0lcnbIVSkewMQ==", "span_id": "ju+tlF3hV+4=", "trace_state": "", "parent_span_id": "rNhyTzfLpZM=", "name": "start_node", "start_time_unix_nano": 1759697139456921200, "end_time_unix_nano": 1759697139460436800, "attributes": {"metadata": "{\"thread_id\": \"1\", \"langgraph_step\": 1, \"langgraph_node\": \"start_node\", \"langgraph_triggers\": [\"branch:to:start_node\"], \"langgraph_path\": [\"__pregel_pull\", \"start_node\"], \"langgraph_checkpoint_ns\": \"start_node:84813bed-3166-803f-e4a5-fa4d5a5a8a9e\"}", "mlflow.spanType": "\"CHAIN\"", "mlflow.spanInputs": "{\"content\": []}", "mlflow.traceRequestId": "\"tr-7d338e153886bb495c9db2154a47b031\""}, "events": [{"time_unix_nano": 1759697139459164, "name": "exception", "attributes": {"exception.message": "'input_str'", "exception.type": "KeyError", "exception.stacktrace": "Traceback (most recent call last):\n  File \"C:\\Users\\tejsh\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\langgraph\\_internal\\_runnable.py\", line 657, in invoke\n    input = context.run(step.invoke, input, config, **kwargs)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\tejsh\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\langgraph\\_internal\\_runnable.py\", line 401, in invoke\n    ret = self.func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\tejsh\\AppData\\Local\\Temp\\ipykernel_14544\\4021691321.py\", line 31, in start_node\n    HumanMessage(content=state['input_str'])\n                         ~~~~~^^^^^^^^^^^^^\nKeyError: 'input_str'"}}], "status": {"message": "'input_str'", "code": "STATUS_CODE_ERROR"}}]}